/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Feedback {
  'id' : bigint,
  'orderId' : OrderId,
  'comment' : [] | [string],
  'timestamp' : Timestamp,
  'rating' : bigint,
}
export type ItemVariant = { 'full' : null } |
  { 'half' : null } |
  { 'regular' : null };
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'timestamp' : Timestamp,
  'phone' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
  'variant' : ItemVariant,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'ready' : null };
export interface PlaceOrderRequest {
  'customerName' : string,
  'phone' : string,
  'items' : Array<OrderItem>,
}
export interface PlaceOrderResponse {
  'orderId' : OrderId,
  'message' : string,
  'totalPrice' : bigint,
}
export interface SubmitFeedbackRequest {
  'orderId' : OrderId,
  'comment' : [] | [string],
  'rating' : bigint,
}
export interface SubmitFeedbackResponse {
  'message' : string,
  'success' : boolean,
}
export type Timestamp = bigint;
export interface _SERVICE {
  'getFeedbacks' : ActorMethod<[], Array<Feedback>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'placeOrder' : ActorMethod<[PlaceOrderRequest], PlaceOrderResponse>,
  'submitFeedback' : ActorMethod<
    [SubmitFeedbackRequest],
    SubmitFeedbackResponse
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];