/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'orderId' : OrderId,
  'comment' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
  'rating' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'ready' : IDL.Null,
});
export const ItemVariant = IDL.Variant({
  'full' : IDL.Null,
  'half' : IDL.Null,
  'regular' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'variant' : ItemVariant,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'timestamp' : Timestamp,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Nat,
});
export const PlaceOrderRequest = IDL.Record({
  'customerName' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
});
export const PlaceOrderResponse = IDL.Record({
  'orderId' : OrderId,
  'message' : IDL.Text,
  'totalPrice' : IDL.Nat,
});
export const SubmitFeedbackRequest = IDL.Record({
  'orderId' : OrderId,
  'comment' : IDL.Opt(IDL.Text),
  'rating' : IDL.Nat,
});
export const SubmitFeedbackResponse = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  'getFeedbacks' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderRequest], [PlaceOrderResponse], []),
  'submitFeedback' : IDL.Func(
      [SubmitFeedbackRequest],
      [SubmitFeedbackResponse],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'orderId' : OrderId,
    'comment' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
    'rating' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'ready' : IDL.Null,
  });
  const ItemVariant = IDL.Variant({
    'full' : IDL.Null,
    'half' : IDL.Null,
    'regular' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'variant' : ItemVariant,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'timestamp' : Timestamp,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Nat,
  });
  const PlaceOrderRequest = IDL.Record({
    'customerName' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
  });
  const PlaceOrderResponse = IDL.Record({
    'orderId' : OrderId,
    'message' : IDL.Text,
    'totalPrice' : IDL.Nat,
  });
  const SubmitFeedbackRequest = IDL.Record({
    'orderId' : OrderId,
    'comment' : IDL.Opt(IDL.Text),
    'rating' : IDL.Nat,
  });
  const SubmitFeedbackResponse = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    'getFeedbacks' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderRequest], [PlaceOrderResponse], []),
    'submitFeedback' : IDL.Func(
        [SubmitFeedbackRequest],
        [SubmitFeedbackResponse],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };