/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SubmitFeedbackRequest {
    orderId: OrderId;
    comment?: string;
    rating: bigint;
}
export interface PlaceOrderRequest {
    customerName: string;
    phone: string;
    items: Array<OrderItem>;
}
export type Timestamp = bigint;
export interface OrderItem {
    name: string;
    quantity: bigint;
    unitPrice: bigint;
    variant: ItemVariant;
}
export interface Feedback {
    id: bigint;
    orderId: OrderId;
    comment?: string;
    timestamp: Timestamp;
    rating: bigint;
}
export interface PlaceOrderResponse {
    orderId: OrderId;
    message: string;
    totalPrice: bigint;
}
export interface Order {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    timestamp: Timestamp;
    phone: string;
    items: Array<OrderItem>;
    totalPrice: bigint;
}
export interface SubmitFeedbackResponse {
    message: string;
    success: boolean;
}
export type OrderId = bigint;
export enum ItemVariant {
    full = "full",
    half = "half",
    regular = "regular"
}
export enum OrderStatus {
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed",
    ready = "ready"
}
export interface backendInterface {
    getFeedbacks(): Promise<Array<Feedback>>;
    getOrders(): Promise<Array<Order>>;
    placeOrder(req: PlaceOrderRequest): Promise<PlaceOrderResponse>;
    submitFeedback(req: SubmitFeedbackRequest): Promise<SubmitFeedbackResponse>;
}
import type { Feedback as _Feedback, ItemVariant as _ItemVariant, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PlaceOrderRequest as _PlaceOrderRequest, SubmitFeedbackRequest as _SubmitFeedbackRequest, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getFeedbacks(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedbacks();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedbacks();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: PlaceOrderRequest): Promise<PlaceOrderResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_PlaceOrderRequest_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_PlaceOrderRequest_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitFeedback(arg0: SubmitFeedbackRequest): Promise<SubmitFeedbackResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(to_candid_SubmitFeedbackRequest_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(to_candid_SubmitFeedbackRequest_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Feedback_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Feedback): Feedback {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ItemVariant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemVariant): ItemVariant {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_OrderItem_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    quantity: bigint;
    unitPrice: bigint;
    variant: _ItemVariant;
}): {
    name: string;
    quantity: bigint;
    unitPrice: bigint;
    variant: ItemVariant;
} {
    return {
        name: value.name,
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        variant: from_candid_ItemVariant_n13(_uploadFile, _downloadFile, value.variant)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    orderId: _OrderId;
    comment: [] | [string];
    timestamp: _Timestamp;
    rating: bigint;
}): {
    id: bigint;
    orderId: OrderId;
    comment?: string;
    timestamp: Timestamp;
    rating: bigint;
} {
    return {
        id: value.id,
        orderId: value.orderId,
        comment: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.comment)),
        timestamp: value.timestamp,
        rating: value.rating
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    timestamp: _Timestamp;
    phone: string;
    items: Array<_OrderItem>;
    totalPrice: bigint;
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    timestamp: Timestamp;
    phone: string;
    items: Array<OrderItem>;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n8(_uploadFile, _downloadFile, value.status),
        timestamp: value.timestamp,
        phone: value.phone,
        items: from_candid_vec_n10(_uploadFile, _downloadFile, value.items),
        totalPrice: value.totalPrice
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    full: null;
} | {
    half: null;
} | {
    regular: null;
}): ItemVariant {
    return "full" in value ? ItemVariant.full : "half" in value ? ItemVariant.half : "regular" in value ? ItemVariant.regular : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    ready: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : "ready" in value ? OrderStatus.ready : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Feedback>): Array<Feedback> {
    return value.map((x)=>from_candid_Feedback_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ItemVariant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemVariant): _ItemVariant {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_OrderItem_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderItem): _OrderItem {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceOrderRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderRequest): _PlaceOrderRequest {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitFeedbackRequest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitFeedbackRequest): _SubmitFeedbackRequest {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    phone: string;
    items: Array<OrderItem>;
}): {
    customerName: string;
    phone: string;
    items: Array<_OrderItem>;
} {
    return {
        customerName: value.customerName,
        phone: value.phone,
        items: to_candid_vec_n17(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    quantity: bigint;
    unitPrice: bigint;
    variant: ItemVariant;
}): {
    name: string;
    quantity: bigint;
    unitPrice: bigint;
    variant: _ItemVariant;
} {
    return {
        name: value.name,
        quantity: value.quantity,
        unitPrice: value.unitPrice,
        variant: to_candid_ItemVariant_n20(_uploadFile, _downloadFile, value.variant)
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    orderId: OrderId;
    comment?: string;
    rating: bigint;
}): {
    orderId: _OrderId;
    comment: [] | [string];
    rating: bigint;
} {
    return {
        orderId: value.orderId,
        comment: value.comment ? candid_some(value.comment) : candid_none(),
        rating: value.rating
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemVariant): {
    full: null;
} | {
    half: null;
} | {
    regular: null;
} {
    return value == ItemVariant.full ? {
        full: null
    } : value == ItemVariant.half ? {
        half: null
    } : value == ItemVariant.regular ? {
        regular: null
    } : value;
}
function to_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderItem>): Array<_OrderItem> {
    return value.map((x)=>to_candid_OrderItem_n18(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
