/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// It should not be manually edited.

// Import Routes

import { Route as rootRoute } from "./routes/__root";

import { Route as CartLazyImport } from "./routes/cart.lazy";
import { Route as CheckoutLazyImport } from "./routes/checkout.lazy";
import { Route as FeedbackLazyImport } from "./routes/feedback.lazy";
import { Route as IndexLazyImport } from "./routes/index.lazy";
import { Route as OrderConfirmLazyImport } from "./routes/order-confirm.lazy";
import { Route as QrLazyImport } from "./routes/qr.lazy";

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as never);

const CartLazyRoute = CartLazyImport.update({
  id: "/cart",
  path: "/cart",
  getParentRoute: () => rootRoute,
} as never);

const CheckoutLazyRoute = CheckoutLazyImport.update({
  id: "/checkout",
  path: "/checkout",
  getParentRoute: () => rootRoute,
} as never);

const FeedbackLazyRoute = FeedbackLazyImport.update({
  id: "/feedback",
  path: "/feedback",
  getParentRoute: () => rootRoute,
} as never);

const OrderConfirmLazyRoute = OrderConfirmLazyImport.update({
  id: "/order-confirm",
  path: "/order-confirm",
  getParentRoute: () => rootRoute,
} as never);

const QrLazyRoute = QrLazyImport.update({
  id: "/qr",
  path: "/qr",
  getParentRoute: () => rootRoute,
} as never);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/cart": {
      id: "/cart";
      path: "/cart";
      fullPath: "/cart";
      preLoaderRoute: typeof CartLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/checkout": {
      id: "/checkout";
      path: "/checkout";
      fullPath: "/checkout";
      preLoaderRoute: typeof CheckoutLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/feedback": {
      id: "/feedback";
      path: "/feedback";
      fullPath: "/feedback";
      preLoaderRoute: typeof FeedbackLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/order-confirm": {
      id: "/order-confirm";
      path: "/order-confirm";
      fullPath: "/order-confirm";
      preLoaderRoute: typeof OrderConfirmLazyImport;
      parentRoute: typeof rootRoute;
    };
    "/qr": {
      id: "/qr";
      path: "/qr";
      fullPath: "/qr";
      preLoaderRoute: typeof QrLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/cart": typeof CartLazyRoute;
  "/checkout": typeof CheckoutLazyRoute;
  "/feedback": typeof FeedbackLazyRoute;
  "/order-confirm": typeof OrderConfirmLazyRoute;
  "/qr": typeof QrLazyRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute;
  "/cart": typeof CartLazyRoute;
  "/checkout": typeof CheckoutLazyRoute;
  "/feedback": typeof FeedbackLazyRoute;
  "/order-confirm": typeof OrderConfirmLazyRoute;
  "/qr": typeof QrLazyRoute;
}

export interface AllRoutesByFullPath {
  "/": typeof IndexLazyRoute;
  "/cart": typeof CartLazyRoute;
  "/checkout": typeof CheckoutLazyRoute;
  "/feedback": typeof FeedbackLazyRoute;
  "/order-confirm": typeof OrderConfirmLazyRoute;
  "/qr": typeof QrLazyRoute;
}

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CartLazyRoute,
  CheckoutLazyRoute,
  FeedbackLazyRoute,
  OrderConfirmLazyRoute,
  QrLazyRoute,
]);
